version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./sites:/etc/nginx/conf.d
    depends_on:
      - drupal-app
    links:
      - drupal-app:drupal_app

  drupal-app:
    image: parv/docker-drupal:v1
    volumes:
      - ./app:/var/www
    ports:
      - "80:80"

  drupal-mysql:
    image: mysql:5.7
    volumes:
      - ~/datadir/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
